### ISSUE TITLE
Items show form has gaps

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#144]
When you look at this form, you see two tables, repairs and inspections. There is a large gap between the two. On smaller screens you may not even realize the inspections are there.

Ideally this should be much smaller. Perhaps the repairs table could grow to the needed size, up to a small maximum.

**Comment by david135** [comment]
This is because of the default setting of `scrollY` for datatables, set to `50vh` (IIRC, half of the vertical window's height).  A height needs to be set, so that we can use the scrollY feature and keep the heading row visible, but 50vh is simply a rough guess for what might work for many tables.  The tables on this page (and possibly others) will need a different value.

**Comment by david135** [comment]
Addressed in #146.
