### ISSUE TITLE
When displaying availabilities on events, partial availability shows twice.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#240]
As shown by the screen shot below, when someone is partially available, it shows that availability twice. One of the columns is a link, and when I hover over it, I can see that they point to the same database record.
The ideal PR would include a test that would expose the bug.
<img width="906" alt="screen shot 2016-10-23 at 6 26 28 pm" src="https://cloud.githubusercontent.com/assets/2431417/19629977/6400bbe2-994e-11e6-814c-bd39021deac4.png">

**Comment by EvanTedesco** [comment]
Can you possibly include steps to reproduce?  Sorry I just forked the repo but need to know how to re create the condition in order to fix it.  When I create an event, then create a single partial availability I only see it once.  Is the bug that the user can potentially create duplicate partial availabilities?

**Comment by kgf** [comment]
They can create a second availability, because the code is not that resilient yet.. but, regarding this issue:
Create an event, note the start and end times.
Create an availability with the same times. (It will do this by default through the UI. It will show as partial, and it will show twice. It seems to be tied to #239

**Comment by EvanTedesco** [comment]
OK I got it sorted thanks

**Comment by kgf** [comment]
Fixed in #245
