### ISSUE TITLE
Add drop down choice for template to New Event

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#254]
When entering a new event, add drop down showing template choices.
Choices should only be events that are categorized as templates.

See Project description for 'Create a New Event from a Template' https://github.com/ReadyResponder/ReadyResponder/projects/2

**Comment by Spandana-Sai** [comment]
@VanAuken so it means in even table one more column should be there with name choices right? Please let me know. Work in progress

**Comment by Spandana-Sai** [comment]
@VanAuken Need a dropdown with choices (inturn nothing but events with category template) so we need to add column in the event model with choices and save event id in it.....am I thinking in the right way? can you please confirm so that I can move forward

**Comment by kgf** [comment]
Not exactly, and I need to change it slightly anyway. 
Right now, you can enter an event and give it a category of meeting, training or template. At the time @VanAuken wrote this, that seemed correct, but it isn't! We need to remove that choice, and instead have a different attribute on an event, a boolean that says `is _template`.
Then we can move to this issue. This is looking for a ui change on the new event form, where you can choose for a list of events. That list would only contain items where `is_template`is true. It could be placed right at the top, before the form partial is loaded.
Does that help?

**Comment by abhishekbose87** [comment]
Hey @kgf , tell me if I understood this correct.

We need to add `is_template` field to `event` model to differentiate between a _template event_ and a _regular event_. And have a form field `template` for having the various templates as options.

Also, what would happen if somebody selected a template, would that create changes on the form. What is the requirement behind selecting a template.

**Comment by kgf** [comment]
You have the basic idea. I want to be able to designate an event as a template. At fist, it was in the category, like meeting or training. But then I realized that was wrong, because then the event created from the template would not know what category to be.
So now I'm looking for a separate field on the form to designate "This is a template". There would be a second field, a drop down select, that would allow you to pick from a list of events that had the first option "True".
There is a second issue, #260 to actually do the work of copying.

 Would you like to claim this issue ?
Thanks for your help.
Kevin

**Comment by abhishekbose87** [comment]
Thanks for explaining it to me 👍 

I will send a PR for this one soon.
