### ISSUE TITLE
person image not displaying properly 

### ISSUE THREAD

**Issue by DJG86g** [ReadyResponder/ReadyResponder#306]
uploaded image and it was uploaded successfully and it is not showing the image. it shows a broken image link and the name of file.

**Comment by houhoulis** [comment]
Thanks @DJG86g !  I am seeing the same problem.

I'm not sure where you saw this behavior, or how many filenames you tested with.  But I can see a routing error locally if I use a file with dots in its name, such as "`Pic 2017-01-01 at 10.10.10am.png`".  With the routing error, I see the filename in the browser rather than the picture, as you reported.

This appears to be Rails behaving as designed.  See
 http://guides.rubyonrails.org/routing.html#dynamic-segments

One fix I found [on Stackoverflow](http://stackoverflow.com/a/5369702) is to change the route declaration to allow dots in the image filename:

```ruby
  get '/uploads/person/portrait/:id/:basename.:extension', controller: 'people',
    action: 'download', type: 'portrait',
    constraints: { basename: /[^\/]+/ }  # <--- this "constraints" part would be new
```

But I'd rather handle filenames a bit more carefully, for a couple reasons.  One is it feels sort of creepy to show the person's original filename in everyone's browser network activity.  Another is I worry we might hit additional edge cases where the filename causes problems in Rails.  Including possible hacking attempts, where someone attempts to get ReadyResponder to misinterpret malformed filenames.  (The Carrierwave [README](https://github.com/carrierwaveuploader/carrierwave#filenames-and-unicode-chars) mentions this briefly.)

I think Carrierwave might have an option to generate a filename based on the hash of the contents.  If we can make use of a Carrierwave feature like that, that feels smarter than dancing around edge cases ourselves.  If not, then (from the README) at least we could set the `sanitize_regexp` = something strict like `/[^[:word:]\-]/` (strip out everything from filenames except the letters, numbers, underscores, and dashes)

**Comment by kgf** [comment]
Thanks for the info @houhoulis I also like the hash approach, as an additional layer of security. If someone did gain access to the filesystem, they could not predict the names, nor match names to faces.

**Comment by kgf** [comment]
Update on the initial issue, it resolved itself. This was probably due to the thumbnail not being generated yet.

**Comment by houhoulis** [comment]
I don't know where @DJG86g observed the bug initially, and/or whether @kgf is referring to the same environment, but the problematic behavior seems easy to reproduce.  Use a file with dots in its name, such as "`Pic 2017-01-01 at 10.10.10am.png`". 

@kgf , are you saying you do not see the same problem?  (If so, I wonder if the behavior is specific to certain operating systems.)

**Comment by kgf** [comment]
That is correct, the production example is no longer broken. I will test it again on Sunday. Thanks for looking into it. Either way, we should deal with the period issue. 
Kevin

**Comment by kgf** [comment]
This came up again recently. I now believe this may be related to permissions. Will need to look at Ability class

**Comment by kgf** [comment]
Based on this line, I wonder if PotraitUploader is the correct model to allow in Ability class.

https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/person.rb#L6

The reason I think is permissions is that I never see the issue as a manager level access, and others always see the issue.

This is the line that gives the manager the permission to see the potrait.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/ability.rb#L11

**Comment by houhoulis** [comment]
I identified a bug, which I described in [this comment](https://github.com/ReadyResponder/ReadyResponder/issues/306#issuecomment-269888392) above.  I gave instructions on how to reproduce it in [this comment](https://github.com/ReadyResponder/ReadyResponder/issues/306#issuecomment-271043348).  I can still reproduce it.

Perhaps @kgf you have identified a different issue.

**Comment by kgf** [comment]
I have identified that we also need to add the `download` action for the person in the `app/models/ability.rb` file
