### ISSUE TITLE
If someone is available after the end time of an event, they are shown as partially available

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#378]
If an event is from 1800 until 2300, and someone has availability of 1800 until 2345, it will be correctly shown in the boxes as available, but in the table it will be shown as partially available.
![screen shot 2017-03-06 at 10 58 20 am](https://cloud.githubusercontent.com/assets/2431417/23617702/ed556318-025b-11e7-9ef2-57994ee275b7.png)

![screen shot 2017-03-06 at 11 00 31 am](https://cloud.githubusercontent.com/assets/2431417/23617782/2f54af44-025c-11e7-9abe-eee3b3696d77.png)

This two parts of the ui should use the same backend code, so they can't diverge. Also, the PR to resolve this should include additional tests.

Thanks

**Comment by kgf** [comment]
@danielstrimpel has offered to help.
Thanks !

**Comment by kgf** [comment]
Any progress, @danielstrimpel ? Any questions ?

**Comment by ghost** [comment]
Hi Kevin,

Thanks for checking in. I haven’t managed to get to it yet. Tomorrow’s crazy but I plan to give it some attention on Friday, hopefully to fix it without too much trouble.

Thanks,
Daniel
-
Daniel Strimpel
dastrimpel@gmail.com <mailto:dastrimpel@gmail.com>
Blog: https://medium.com/@dastrimpel
Github: https://github.com/danielstrimpel

**Comment by ghost** [comment]
Hi Kevin,

I just tried to get it up and running locally. During bundle install, I had a problem with RMagic. The log file is:

find_executable: checking for clang... -------------------- yes

--------------------

find_executable: checking for Magick-config... -------------------- no

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------

Detected ImageMagick version: 
Can't install RMagick 2.15.4. You must have ImageMagick 6.4.9 or later.
Can't install RMagick 2.15.4. You must have ImageMagick 6.4.9 or later.


After that, 
bundle exec rake db:create
failed because the bundle install was messed up. Any advice?

Also, there seems to be a password to get into the slack channel. Can you give me access?

Thanks,
Daniel

-
Daniel Strimpel
dastrimpel@gmail.com <mailto:dastrimpel@gmail.com>
Blog: https://medium.com/@dastrimpel
Github: https://github.com/danielstrimpel

**Comment by goldenhub77** [comment]
@danielstrimpel I meant to add this to the install documentation last pull request. Imagemagick is a dependency for Rmagick. You must run 'brew update && brew install imagemagick' successfully before Rmagick can be installed.

**Comment by kgf** [comment]
@goldenhub77 thanks for your help ! Did that resolve the issue ?

**Comment by ghost** [comment]
I ran what you said.

Now, when I do bundle install, it fails to build the rmagick gem and says:
"Can't install RMagick 2.15.4. Can't find MagickWand.h"
-
Daniel Strimpel
dastrimpel@gmail.com <mailto:dastrimpel@gmail.com>
Blog: https://medium.com/@dastrimpel
Github: https://github.com/danielstrimpel

**Comment by goldenhub77** [comment]
@danielstrimpel  it turns out the most recent version of imagemagick is not compatible with the Rmagick gem version used in this app. run the following commands and let me know if it works now:
brew unlink imagemagick
brew install imagemagick@6 && brew link imagemagick@6 --force

**Comment by goldenhub77** [comment]
@danielstrimpel one additional note - run brew uninstall imagemagick first if you want to remove the most recent version you already installed.

**Comment by ghost** [comment]
Successfully running the site locally now, thanks!

**Comment by ghost** [comment]
Ran into another issue: I seem to get "access denied" for everything on the site. How do I give myself access? Should I just set my users role to be Manager?

**Comment by goldenhub77** [comment]
@danielstrimpel When you run rake:seed for the first time it returns to the console a manager email/password to login with full access. You can wipe the database and rerun those initial rake commands to get a new one if you need to.

Initial setup commands:
rake db:create
rake db:schema:load
rake db:seed 
rake db:test:prepare

**Comment by goldenhub77** [comment]
@danielstrimpel To answer your second question yes you can just change your roles in Rails console if you prefer.

**Comment by ghost** [comment]
Great thanks

**Comment by ghost** [comment]
Submitted PR : https://github.com/ReadyResponder/ReadyResponder/pull/444

**Comment by kgf** [comment]
Closed by #444
