### ISSUE TITLE
In Event, minimum title does not exclude lesser titles

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#611]
An Event with a minimum title of officer, will still show CERT members, may show recruits (uncertain).  If there is a simultaneous event for CERT, the second event will show CERT members as having not responded.

The Event should work that a minimum title officer will exclude all CERT members from showing up as available, unavailable, partially available and also not show as no response regardless if they are available at the same time.

This may be related to #606

**Comment by kgf** [comment]
This is due to the comparison being the wrong direction. Higher ranked people have lower numbers.
The fix for this is easy, but I'd really appreciate a PR that included some tests !
Offending line is here. ->
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L94
Thanks for your help !
Kevin

**Comment by yasirazgar** [comment]
@VanAuken @kgf, I cant understand the issue completely, can you guys please provide some additional details.
Thanks!

**Comment by kgf** [comment]
The bug portion of this was fixed by #623. I will close this. 

This could use some tests though !Especially around the `unknown` box on the Event show
