### ISSUE TITLE
When entering an availability, there is a cryptic error message

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#656]
The message says to correct the errors below. I believe the problem is the validation for no overlapping availabilities, located as shown below. This theory was tested using various availability start and end times
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/availability.rb#L10

**Comment by goldenhub77** [comment]
@kgf This error_notification does not display because it doesn't have a corresponding input field associated with it. I added a loop to display full error messages right below the error_notification so users will understand why its failing. How do you want availabilities to be validated in a overlap situation?

**Comment by goldenhub77** [comment]
@kgf refer to PR #692

**Comment by kgf** [comment]
@goldenhub77  I believe this was closed by #692, as you referenced above.
