### ISSUE TITLE
Add tests to event#show availabilities table

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#679]
We have had recent examples of this table not showing people. There was a change that attempted to fix this, and then we got duplicates.
This issue is only looking for the tests.

**Comment by kgf** [comment]
This is the line that renders the table of interest
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/events/show.html.erb#L77

**Comment by kgf** [comment]
When setting up the test cases, you'll want multiple availabilities 

1. One that starts before the event and ends during the event (Counts as partially available)
2. One that starts during the event, and ends after the event. (Counts as partially available)
3. One that starts and ends during the event (Counts as partially available)
4. One that starts before the event and ends after the event (Counts as fully available)
5. One that starts and ends before the event (Should not appear in the table)
6. One that starts and ends after the event. (Should not appear in the table)
7. One that starts and ends at the same times as the event (Counts as fully available)

Ideally there should be one or more availability records showing available for each of those, and one or more availability record set to unavailable for each of those time periods.

**Comment by johnschoeman** [comment]
ping: @houhoulis & @kgf 

<img width="1272" alt="screen shot 2018-03-20 at 1 34 17 pm" src="https://user-images.githubusercontent.com/16049495/37801397-ddc20adc-2dfc-11e8-8098-a7dab65c0ede.png">


done with the first pass at these tests.  see [PR](https://github.com/ReadyResponder/ReadyResponder/pull/683)

I wasn't sure of the intended behavior, since the feature is currently not working.

Questions: 

- are partial availabilities supposed to be showing on the availability table?  If so, how are they indicated as partially available?

- are availabilities that have the status as unavailable supposed to show up on the table if the start/end times are such that the availability is considered full or partial?

- currently there is test coverage on the model level and controller under the context of 'responses'.  What is the distinction between a response and an availability?  do these tests need to be looked at again?

**Comment by kgf** [comment]
John, thanks for your help !
Yes, partial availabilities should show up on the availabilities table. they are designated by a yellow background. Fully available is green, and unavailable is red. 
In addition to availabilities, assignments also show in this table as blue. This is to help those scheduling to see who already has an assignment. There are almost certainly better ways to do this, but that's what we have for now.
No matter the time span, unavailable shows as red.
Responses are availabilities. Wether you said you were available or unavailable, you have responded.
I hope this helps, and I'll be about today if you have more questions.
Thanks again,
Kevin

**Comment by goldenhub77** [comment]
@kgf my PR #692 includes tests for most if not all of this. I had to write them to fix a prior issue. let me know if the tests are satisfactory

**Comment by kgf** [comment]
Fixed by #705 & #692
