### ISSUE TITLE
Can new users be added?

### ISSUE THREAD

**Issue by grichardomi** [ReadyResponder/ReadyResponder#767]
I'm not seeing any way to add new users. Is it possible?

**Comment by kgf** [comment]
Thanks for your interest.
Since ready responder is never a social app, we didn't make creating an account a key feature. However, from the sign in screen, you can sign up, which creates an account without any privileges. An admin can then as the appropriate roles.
If you're setting up a new installation, the setup script will output am admin username and password at the end.
Does this answer your question?

**Comment by grichardomi** [comment]
Got it.

I appreciate the follow-up.

Thank you
